export interface CountryOption {
  value: string;
  label: string;
  dialCode: string;
  flag: string;
  minDigits: number;
  maxDigits: number;
  prefixes?: string[];
}

export const COUNTRIES: CountryOption[] = [
  { value: 'AF', label: 'Afghanistan',             dialCode: '+93',   flag: 'AF', minDigits: 9,  maxDigits: 9  },
  { value: 'AL', label: 'Albania',                 dialCode: '+355',  flag: 'AL', minDigits: 9,  maxDigits: 9  },
  { value: 'DZ', label: 'Algeria',                 dialCode: '+213',  flag: 'DZ', minDigits: 9,  maxDigits: 9,  prefixes: ['05','06','07'] },
  { value: 'AO', label: 'Angola',                  dialCode: '+244',  flag: 'AO', minDigits: 9,  maxDigits: 9  },
  { value: 'AR', label: 'Argentina',               dialCode: '+54',   flag: 'AR', minDigits: 10, maxDigits: 10 },
  { value: 'AM', label: 'Armenia',                 dialCode: '+374',  flag: 'AM', minDigits: 8,  maxDigits: 8  },
  { value: 'AU', label: 'Australia',               dialCode: '+61',   flag: 'AU', minDigits: 9,  maxDigits: 9,  prefixes: ['04'] },
  { value: 'AT', label: 'Austria',                 dialCode: '+43',   flag: 'AT', minDigits: 10, maxDigits: 13 },
  { value: 'AZ', label: 'Azerbaijan',              dialCode: '+994',  flag: 'AZ', minDigits: 9,  maxDigits: 9  },
  { value: 'BH', label: 'Bahrain',                 dialCode: '+973',  flag: 'BH', minDigits: 8,  maxDigits: 8  },
  { value: 'BD', label: 'Bangladesh',              dialCode: '+880',  flag: 'BD', minDigits: 10, maxDigits: 10, prefixes: ['01'] },
  { value: 'BY', label: 'Belarus',                 dialCode: '+375',  flag: 'BY', minDigits: 9,  maxDigits: 9  },
  { value: 'BE', label: 'Belgium',                 dialCode: '+32',   flag: 'BE', minDigits: 8,  maxDigits: 9  },
  { value: 'BJ', label: 'Benin',                   dialCode: '+229',  flag: 'BJ', minDigits: 8,  maxDigits: 8  },
  { value: 'BO', label: 'Bolivia',                 dialCode: '+591',  flag: 'BO', minDigits: 8,  maxDigits: 8  },
  { value: 'BA', label: 'Bosnia and Herzegovina',  dialCode: '+387',  flag: 'BA', minDigits: 8,  maxDigits: 8  },
  { value: 'BW', label: 'Botswana',                dialCode: '+267',  flag: 'BW', minDigits: 8,  maxDigits: 8  },
  { value: 'BR', label: 'Brazil',                  dialCode: '+55',   flag: 'BR', minDigits: 10, maxDigits: 11 },
  { value: 'BN', label: 'Brunei',                  dialCode: '+673',  flag: 'BN', minDigits: 7,  maxDigits: 7  },
  { value: 'BG', label: 'Bulgaria',                dialCode: '+359',  flag: 'BG', minDigits: 9,  maxDigits: 9  },
  { value: 'BF', label: 'Burkina Faso',            dialCode: '+226',  flag: 'BF', minDigits: 8,  maxDigits: 8  },
  { value: 'BI', label: 'Burundi',                 dialCode: '+257',  flag: 'BI', minDigits: 8,  maxDigits: 8  },
  { value: 'KH', label: 'Cambodia',                dialCode: '+855',  flag: 'KH', minDigits: 8,  maxDigits: 9  },
  { value: 'CM', label: 'Cameroon',                dialCode: '+237',  flag: 'CM', minDigits: 9,  maxDigits: 9  },
  { value: 'CA', label: 'Canada',                  dialCode: '+1',    flag: 'CA', minDigits: 10, maxDigits: 10 },
  { value: 'CF', label: 'Central African Rep.',    dialCode: '+236',  flag: 'CF', minDigits: 8,  maxDigits: 8  },
  { value: 'TD', label: 'Chad',                    dialCode: '+235',  flag: 'TD', minDigits: 8,  maxDigits: 8  },
  { value: 'CL', label: 'Chile',                   dialCode: '+56',   flag: 'CL', minDigits: 9,  maxDigits: 9  },
  { value: 'CN', label: 'China',                   dialCode: '+86',   flag: 'CN', minDigits: 11, maxDigits: 11, prefixes: ['1'] },
  { value: 'CO', label: 'Colombia',                dialCode: '+57',   flag: 'CO', minDigits: 10, maxDigits: 10 },
  { value: 'CG', label: 'Congo',                   dialCode: '+242',  flag: 'CG', minDigits: 9,  maxDigits: 9  },
  { value: 'CD', label: 'Congo (DRC)',             dialCode: '+243',  flag: 'CD', minDigits: 9,  maxDigits: 9  },
  { value: 'CR', label: 'Costa Rica',              dialCode: '+506',  flag: 'CR', minDigits: 8,  maxDigits: 8  },
  { value: 'HR', label: 'Croatia',                 dialCode: '+385',  flag: 'HR', minDigits: 8,  maxDigits: 9  },
  { value: 'CU', label: 'Cuba',                    dialCode: '+53',   flag: 'CU', minDigits: 8,  maxDigits: 8  },
  { value: 'CY', label: 'Cyprus',                  dialCode: '+357',  flag: 'CY', minDigits: 8,  maxDigits: 8  },
  { value: 'CZ', label: 'Czech Republic',          dialCode: '+420',  flag: 'CZ', minDigits: 9,  maxDigits: 9  },
  { value: 'DK', label: 'Denmark',                 dialCode: '+45',   flag: 'DK', minDigits: 8,  maxDigits: 8  },
  { value: 'DJ', label: 'Djibouti',                dialCode: '+253',  flag: 'DJ', minDigits: 8,  maxDigits: 8  },
  { value: 'DO', label: 'Dominican Republic',      dialCode: '+1809', flag: 'DO', minDigits: 7,  maxDigits: 7  },
  { value: 'EC', label: 'Ecuador',                 dialCode: '+593',  flag: 'EC', minDigits: 9,  maxDigits: 9  },
  { value: 'EG', label: 'Egypt',                   dialCode: '+20',   flag: 'EG', minDigits: 10, maxDigits: 10 },
  { value: 'SV', label: 'El Salvador',             dialCode: '+503',  flag: 'SV', minDigits: 8,  maxDigits: 8  },
  { value: 'ER', label: 'Eritrea',                 dialCode: '+291',  flag: 'ER', minDigits: 7,  maxDigits: 7  },
  { value: 'EE', label: 'Estonia',                 dialCode: '+372',  flag: 'EE', minDigits: 7,  maxDigits: 8  },
  { value: 'ET', label: 'Ethiopia',                dialCode: '+251',  flag: 'ET', minDigits: 9,  maxDigits: 9,  prefixes: ['09','9','07','7'] },
  { value: 'FJ', label: 'Fiji',                    dialCode: '+679',  flag: 'FJ', minDigits: 7,  maxDigits: 7  },
  { value: 'FI', label: 'Finland',                 dialCode: '+358',  flag: 'FI', minDigits: 9,  maxDigits: 11 },
  { value: 'FR', label: 'France',                  dialCode: '+33',   flag: 'FR', minDigits: 9,  maxDigits: 9,  prefixes: ['0'] },
  { value: 'GA', label: 'Gabon',                   dialCode: '+241',  flag: 'GA', minDigits: 7,  maxDigits: 8  },
  { value: 'GM', label: 'Gambia',                  dialCode: '+220',  flag: 'GM', minDigits: 7,  maxDigits: 7  },
  { value: 'GE', label: 'Georgia',                 dialCode: '+995',  flag: 'GE', minDigits: 9,  maxDigits: 9  },
  { value: 'DE', label: 'Germany',                 dialCode: '+49',   flag: 'DE', minDigits: 10, maxDigits: 12 },
  { value: 'GH', label: 'Ghana',                   dialCode: '+233',  flag: 'GH', minDigits: 9,  maxDigits: 9,  prefixes: ['02','05'] },
  { value: 'GR', label: 'Greece',                  dialCode: '+30',   flag: 'GR', minDigits: 10, maxDigits: 10 },
  { value: 'GT', label: 'Guatemala',               dialCode: '+502',  flag: 'GT', minDigits: 8,  maxDigits: 8  },
  { value: 'GN', label: 'Guinea',                  dialCode: '+224',  flag: 'GN', minDigits: 9,  maxDigits: 9  },
  { value: 'GY', label: 'Guyana',                  dialCode: '+592',  flag: 'GY', minDigits: 7,  maxDigits: 7  },
  { value: 'HT', label: 'Haiti',                   dialCode: '+509',  flag: 'HT', minDigits: 8,  maxDigits: 8  },
  { value: 'HN', label: 'Honduras',                dialCode: '+504',  flag: 'HN', minDigits: 8,  maxDigits: 8  },
  { value: 'HU', label: 'Hungary',                 dialCode: '+36',   flag: 'HU', minDigits: 9,  maxDigits: 9  },
  { value: 'IS', label: 'Iceland',                 dialCode: '+354',  flag: 'IS', minDigits: 7,  maxDigits: 7  },
  { value: 'IN', label: 'India',                   dialCode: '+91',   flag: 'IN', minDigits: 10, maxDigits: 10, prefixes: ['6','7','8','9'] },
  { value: 'ID', label: 'Indonesia',               dialCode: '+62',   flag: 'ID', minDigits: 9,  maxDigits: 12, prefixes: ['08'] },
  { value: 'IR', label: 'Iran',                    dialCode: '+98',   flag: 'IR', minDigits: 10, maxDigits: 10 },
  { value: 'IQ', label: 'Iraq',                    dialCode: '+964',  flag: 'IQ', minDigits: 10, maxDigits: 10 },
  { value: 'IE', label: 'Ireland',                 dialCode: '+353',  flag: 'IE', minDigits: 9,  maxDigits: 9  },
  { value: 'IL', label: 'Israel',                  dialCode: '+972',  flag: 'IL', minDigits: 9,  maxDigits: 9  },
  { value: 'IT', label: 'Italy',                   dialCode: '+39',   flag: 'IT', minDigits: 9,  maxDigits: 10 },
  { value: 'JM', label: 'Jamaica',                 dialCode: '+1876', flag: 'JM', minDigits: 7,  maxDigits: 7  },
  { value: 'JP', label: 'Japan',                   dialCode: '+81',   flag: 'JP', minDigits: 10, maxDigits: 10 },
  { value: 'JO', label: 'Jordan',                  dialCode: '+962',  flag: 'JO', minDigits: 9,  maxDigits: 9  },
  { value: 'KZ', label: 'Kazakhstan',              dialCode: '+7',    flag: 'KZ', minDigits: 10, maxDigits: 10 },
  { value: 'KE', label: 'Kenya',                   dialCode: '+254',  flag: 'KE', minDigits: 9,  maxDigits: 9,  prefixes: ['07','01'] },
  { value: 'KW', label: 'Kuwait',                  dialCode: '+965',  flag: 'KW', minDigits: 8,  maxDigits: 8  },
  { value: 'KG', label: 'Kyrgyzstan',              dialCode: '+996',  flag: 'KG', minDigits: 9,  maxDigits: 9  },
  { value: 'LA', label: 'Laos',                    dialCode: '+856',  flag: 'LA', minDigits: 8,  maxDigits: 10 },
  { value: 'LV', label: 'Latvia',                  dialCode: '+371',  flag: 'LV', minDigits: 8,  maxDigits: 8  },
  { value: 'LB', label: 'Lebanon',                 dialCode: '+961',  flag: 'LB', minDigits: 7,  maxDigits: 8  },
  { value: 'LS', label: 'Lesotho',                 dialCode: '+266',  flag: 'LS', minDigits: 8,  maxDigits: 8  },
  { value: 'LR', label: 'Liberia',                 dialCode: '+231',  flag: 'LR', minDigits: 7,  maxDigits: 8  },
  { value: 'LY', label: 'Libya',                   dialCode: '+218',  flag: 'LY', minDigits: 9,  maxDigits: 9  },
  { value: 'LT', label: 'Lithuania',               dialCode: '+370',  flag: 'LT', minDigits: 8,  maxDigits: 8  },
  { value: 'LU', label: 'Luxembourg',              dialCode: '+352',  flag: 'LU', minDigits: 9,  maxDigits: 11 },
  { value: 'MG', label: 'Madagascar',              dialCode: '+261',  flag: 'MG', minDigits: 9,  maxDigits: 9  },
  { value: 'MW', label: 'Malawi',                  dialCode: '+265',  flag: 'MW', minDigits: 9,  maxDigits: 9  },
  { value: 'MY', label: 'Malaysia',                dialCode: '+60',   flag: 'MY', minDigits: 9,  maxDigits: 10, prefixes: ['01'] },
  { value: 'MV', label: 'Maldives',                dialCode: '+960',  flag: 'MV', minDigits: 7,  maxDigits: 7  },
  { value: 'ML', label: 'Mali',                    dialCode: '+223',  flag: 'ML', minDigits: 8,  maxDigits: 8  },
  { value: 'MT', label: 'Malta',                   dialCode: '+356',  flag: 'MT', minDigits: 8,  maxDigits: 8  },
  { value: 'MR', label: 'Mauritania',              dialCode: '+222',  flag: 'MR', minDigits: 8,  maxDigits: 8  },
  { value: 'MU', label: 'Mauritius',               dialCode: '+230',  flag: 'MU', minDigits: 8,  maxDigits: 8  },
  { value: 'MX', label: 'Mexico',                  dialCode: '+52',   flag: 'MX', minDigits: 10, maxDigits: 10 },
  { value: 'MD', label: 'Moldova',                 dialCode: '+373',  flag: 'MD', minDigits: 8,  maxDigits: 8  },
  { value: 'MN', label: 'Mongolia',                dialCode: '+976',  flag: 'MN', minDigits: 8,  maxDigits: 8  },
  { value: 'ME', label: 'Montenegro',              dialCode: '+382',  flag: 'ME', minDigits: 8,  maxDigits: 9  },
  { value: 'MA', label: 'Morocco',                 dialCode: '+212',  flag: 'MA', minDigits: 9,  maxDigits: 9,  prefixes: ['06','07'] },
  { value: 'MZ', label: 'Mozambique',              dialCode: '+258',  flag: 'MZ', minDigits: 9,  maxDigits: 9  },
  { value: 'MM', label: 'Myanmar',                 dialCode: '+95',   flag: 'MM', minDigits: 8,  maxDigits: 10 },
  { value: 'NA', label: 'Namibia',                 dialCode: '+264',  flag: 'NA', minDigits: 9,  maxDigits: 10 },
  { value: 'NP', label: 'Nepal',                   dialCode: '+977',  flag: 'NP', minDigits: 10, maxDigits: 10 },
  { value: 'NL', label: 'Netherlands',             dialCode: '+31',   flag: 'NL', minDigits: 9,  maxDigits: 9  },
  { value: 'NZ', label: 'New Zealand',             dialCode: '+64',   flag: 'NZ', minDigits: 8,  maxDigits: 10 },
  { value: 'NI', label: 'Nicaragua',               dialCode: '+505',  flag: 'NI', minDigits: 8,  maxDigits: 8  },
  { value: 'NE', label: 'Niger',                   dialCode: '+227',  flag: 'NE', minDigits: 8,  maxDigits: 8  },
  { value: 'NG', label: 'Nigeria',                 dialCode: '+234',  flag: 'NG', minDigits: 10, maxDigits: 11, prefixes: ['07','08','09'] },
  { value: 'NO', label: 'Norway',                  dialCode: '+47',   flag: 'NO', minDigits: 8,  maxDigits: 8  },
  { value: 'OM', label: 'Oman',                    dialCode: '+968',  flag: 'OM', minDigits: 8,  maxDigits: 8  },
  { value: 'PK', label: 'Pakistan',                dialCode: '+92',   flag: 'PK', minDigits: 10, maxDigits: 10, prefixes: ['03'] },
  { value: 'PA', label: 'Panama',                  dialCode: '+507',  flag: 'PA', minDigits: 8,  maxDigits: 8  },
  { value: 'PG', label: 'Papua New Guinea',        dialCode: '+675',  flag: 'PG', minDigits: 8,  maxDigits: 8  },
  { value: 'PY', label: 'Paraguay',                dialCode: '+595',  flag: 'PY', minDigits: 9,  maxDigits: 9  },
  { value: 'PE', label: 'Peru',                    dialCode: '+51',   flag: 'PE', minDigits: 9,  maxDigits: 9  },
  { value: 'PH', label: 'Philippines',             dialCode: '+63',   flag: 'PH', minDigits: 10, maxDigits: 10, prefixes: ['09'] },
  { value: 'PL', label: 'Poland',                  dialCode: '+48',   flag: 'PL', minDigits: 9,  maxDigits: 9  },
  { value: 'PT', label: 'Portugal',                dialCode: '+351',  flag: 'PT', minDigits: 9,  maxDigits: 9  },
  { value: 'QA', label: 'Qatar',                   dialCode: '+974',  flag: 'QA', minDigits: 8,  maxDigits: 8  },
  { value: 'RO', label: 'Romania',                 dialCode: '+40',   flag: 'RO', minDigits: 9,  maxDigits: 9  },
  { value: 'RU', label: 'Russia',                  dialCode: '+7',    flag: 'RU', minDigits: 10, maxDigits: 10, prefixes: ['9'] },
  { value: 'RW', label: 'Rwanda',                  dialCode: '+250',  flag: 'RW', minDigits: 9,  maxDigits: 9,  prefixes: ['07'] },
  { value: 'SA', label: 'Saudi Arabia',            dialCode: '+966',  flag: 'SA', minDigits: 9,  maxDigits: 9,  prefixes: ['05'] },
  { value: 'SN', label: 'Senegal',                 dialCode: '+221',  flag: 'SN', minDigits: 9,  maxDigits: 9  },
  { value: 'RS', label: 'Serbia',                  dialCode: '+381',  flag: 'RS', minDigits: 8,  maxDigits: 9  },
  { value: 'SL', label: 'Sierra Leone',            dialCode: '+232',  flag: 'SL', minDigits: 8,  maxDigits: 8  },
  { value: 'SG', label: 'Singapore',               dialCode: '+65',   flag: 'SG', minDigits: 8,  maxDigits: 8  },
  { value: 'SK', label: 'Slovakia',                dialCode: '+421',  flag: 'SK', minDigits: 9,  maxDigits: 9  },
  { value: 'SI', label: 'Slovenia',                dialCode: '+386',  flag: 'SI', minDigits: 8,  maxDigits: 8  },
  { value: 'SO', label: 'Somalia',                 dialCode: '+252',  flag: 'SO', minDigits: 7,  maxDigits: 9  },
  { value: 'ZA', label: 'South Africa',            dialCode: '+27',   flag: 'ZA', minDigits: 9,  maxDigits: 9,  prefixes: ['06','07','08'] },
  { value: 'SS', label: 'South Sudan',             dialCode: '+211',  flag: 'SS', minDigits: 9,  maxDigits: 9  },
  { value: 'ES', label: 'Spain',                   dialCode: '+34',   flag: 'ES', minDigits: 9,  maxDigits: 9  },
  { value: 'LK', label: 'Sri Lanka',               dialCode: '+94',   flag: 'LK', minDigits: 9,  maxDigits: 9  },
  { value: 'SD', label: 'Sudan',                   dialCode: '+249',  flag: 'SD', minDigits: 9,  maxDigits: 9,  prefixes: ['09','01'] },
  { value: 'SE', label: 'Sweden',                  dialCode: '+46',   flag: 'SE', minDigits: 9,  maxDigits: 9  },
  { value: 'CH', label: 'Switzerland',             dialCode: '+41',   flag: 'CH', minDigits: 9,  maxDigits: 9  },
  { value: 'SY', label: 'Syria',                   dialCode: '+963',  flag: 'SY', minDigits: 9,  maxDigits: 9  },
  { value: 'TW', label: 'Taiwan',                  dialCode: '+886',  flag: 'TW', minDigits: 9,  maxDigits: 10 },
  { value: 'TJ', label: 'Tajikistan',              dialCode: '+992',  flag: 'TJ', minDigits: 9,  maxDigits: 9  },
  { value: 'TZ', label: 'Tanzania',                dialCode: '+255',  flag: 'TZ', minDigits: 9,  maxDigits: 9,  prefixes: ['06','07'] },
  { value: 'TH', label: 'Thailand',                dialCode: '+66',   flag: 'TH', minDigits: 9,  maxDigits: 9  },
  { value: 'TG', label: 'Togo',                    dialCode: '+228',  flag: 'TG', minDigits: 8,  maxDigits: 8  },
  { value: 'TT', label: 'Trinidad and Tobago',     dialCode: '+1868', flag: 'TT', minDigits: 7,  maxDigits: 7  },
  { value: 'TN', label: 'Tunisia',                 dialCode: '+216',  flag: 'TN', minDigits: 8,  maxDigits: 8  },
  { value: 'TR', label: 'Turkey',                  dialCode: '+90',   flag: 'TR', minDigits: 10, maxDigits: 10, prefixes: ['05'] },
  { value: 'TM', label: 'Turkmenistan',            dialCode: '+993',  flag: 'TM', minDigits: 8,  maxDigits: 8  },
  { value: 'UG', label: 'Uganda',                  dialCode: '+256',  flag: 'UG', minDigits: 9,  maxDigits: 9,  prefixes: ['07'] },
  { value: 'UA', label: 'Ukraine',                 dialCode: '+380',  flag: 'UA', minDigits: 9,  maxDigits: 9  },
  { value: 'AE', label: 'United Arab Emirates',    dialCode: '+971',  flag: 'AE', minDigits: 9,  maxDigits: 9,  prefixes: ['05'] },
  { value: 'GB', label: 'United Kingdom',          dialCode: '+44',   flag: 'GB', minDigits: 10, maxDigits: 10 },
  { value: 'US', label: 'United States',           dialCode: '+1',    flag: 'US', minDigits: 10, maxDigits: 10 },
  { value: 'UY', label: 'Uruguay',                 dialCode: '+598',  flag: 'UY', minDigits: 8,  maxDigits: 9  },
  { value: 'UZ', label: 'Uzbekistan',              dialCode: '+998',  flag: 'UZ', minDigits: 9,  maxDigits: 9  },
  { value: 'VE', label: 'Venezuela',               dialCode: '+58',   flag: 'VE', minDigits: 10, maxDigits: 10 },
  { value: 'VN', label: 'Vietnam',                 dialCode: '+84',   flag: 'VN', minDigits: 9,  maxDigits: 10 },
  { value: 'YE', label: 'Yemen',                   dialCode: '+967',  flag: 'YE', minDigits: 9,  maxDigits: 9  },
  { value: 'ZM', label: 'Zambia',                  dialCode: '+260',  flag: 'ZM', minDigits: 9,  maxDigits: 9  },
  { value: 'ZW', label: 'Zimbabwe',                dialCode: '+263',  flag: 'ZW', minDigits: 9,  maxDigits: 9  },
];

/** Returns emoji flag from ISO-2 code using regional indicator letters */
export function getFlag(iso2: string): string {
  return iso2.toUpperCase().split('').map(c => String.fromCodePoint(0x1F1E6 + c.charCodeAt(0) - 65)).join('');
}
